<?php

/**
 * @file
 * Contains custom code for sunset policy.
 */

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function nys_sunset_policy_theme() {
  return [
    'expiring_mail' => [
      'variables' => [
        'message' => FALSE,
      ],
    ],
    'expired_mail' => [
      'variables' => [
        'message' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
/**
 * Implements hook_cron().
 */
function sunset_policy_cron() {
  $dispatcher = \Drupal::service('event_dispatcher');

  // Get expiring and expired node IDs.
  $sunsetFunctions = \Drupal::service('sunset_policy.cron');
  $expiringNids = $sunsetFunctions->getExpiring();
  $expiredNids = $sunsetFunctions->getExpired();

  // Dispatch the event.
  $event = new NysSunsetPolicyEvent($expiringNids, $expiredNids);
  $dispatcher->dispatch('nys_sunset_policy.event', $event);
}

/**
 * Implements hook_mail().
 */
function sunset_policy_mail($key, &$message, $params) {
  switch ($key) {
    case 'expired_mail':
    case 'expiring_mail':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}
